on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker builder prune --all --force
          DOCKER_BUILDKIT=0 docker build --file ./Dockerfile --tag my/repo:$(date +%s) fold1/fold2
